[workspace]
resolver="2"
members = [
  "crates/clonpcoat",
  "crates/clonpcoat-dom",
  "crates/clonpcoat-macro",
  "crates/clonpcoat-view",

  "examples/hello-world",
]

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
# Clonpcoat crates
clonpcoat = { path = "crates/clonpcoat" }
clonpcoat-dom = { path = "crates/clonpcoat-dom"}
clonpcoat-macro = { path = "crates/clonpcoat-macro" }
clonpcoat-view = { path = "crates/clonpcoat-view" }

proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.6", features = ["parsing"] }
