[workspace]
resolver="2"
members = [
  "crates/clonpcoat",
  "crates/clonpcoat-macro",
  "crates/clonpcoat-view",

  "examples/hello-world",
]

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
# Clonpcoat crates
clonpcoat = { path = "crates/clonpcoat" }
clonpcoat-macro = { path = "crates/clonpcoat-macro" }
clonpcoat-view = { path = "crates/clonpcoat-view" }
